In [ ]:
# Setup environment
%pip install jupyter notebook ipykernel
# Installation & Setup : CPU-only (simplest, good for learning)
%pip install torch torchvision torchaudio numpy==1.26.4

In [1]:
%pip install numpy==1.26.4

Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
import numpy as np

In [3]:
print(np.__version__)
print(torch.__version__)

1.26.4
2.2.2


In [4]:
print("="*60)
print("Part 1: Creating Tensors from Data")
print("="*60)

Part 1: Creating Tensors from Data


In [5]:
scalar = torch.tensor(7)
print(f"Scalar: {scalar}")
print(f"Scalar ndim: {scalar.ndim}")

Scalar: 7
Scalar ndim: 0


In [6]:
# TODO: Create a vector tensor (1-dimensional)
vector = torch.tensor([1, 2, 3, 4, 5])
print(f"Vector: \n{vector}")
print(f"Vecor shape: {vector.shape}")

Vector: 
tensor([1, 2, 3, 4, 5])
Vecor shape: torch.Size([5])


In [7]:
# TODO: Create a matrix tensor (2-dimensional)
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"Matrix: \n{matrix}")
print(f"Matrix shape: {matrix.shape}")

Matrix: 
tensor([[1, 2, 3],
        [4, 5, 6]])
Matrix shape: torch.Size([2, 3])


In [8]:
# TODO: Create a 3D tensor
tensor_3d = torch.tensor([[[2, 3], [6, 5]], [[1, 3], [7, 9]]])
print(f"3D Tensor:\n{tensor_3d}")
print(f"3D Tensor Shape:{tensor_3d.shape}")

3D Tensor:
tensor([[[2, 3],
         [6, 5]],

        [[1, 3],
         [7, 9]]])
3D Tensor Shape:torch.Size([2, 2, 2])


In [9]:
print("="*60)
print("Part 2: Creating Tensors with Specific Values")
print("="*60)

Part 2: Creating Tensors with Specific Values


In [ ]:
# TODO: Create a tensor filled with zeros
zeros = torch.zeros(3, 4)
print(f"Zeros (3x4):\n{zeros}")

Zeros (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# TODO: Create a tensor filled with ones
ones = torch.ones(3, 2)
print(f"Ones (3x2):\n{ones}")

Ones (3x2):
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
# TODO: Create a tensor filled with a specific value
full = torch.full((2, 3), 9)
print(f"Full (2x3):\n{full}")

Full (2x3):
tensor([[9, 9, 9],
        [9, 9, 9]])


In [ ]:
# TODO: Create identity matrix
identity = torch.eye(4)
print(f"Identity matrix (4x4):\n{identity}")

Identity matrix (4x4):
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [ ]:
# TODO: Create a tensor with values from 0 to 9
range_tensor = torch.arange(0, 10)
print(f"Range (0-9):\n{range_tensor}")

Range (0-9):
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# TODO: Create evenly spaced values
linspace = torch.linspace(0, 10, steps=5)
print(f"Linspace (0-10, 5 steps):\n{linspace}")

Linspace (0-10, 5 steps):
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [16]:
print("="*60)
print("Part 3: Creating Random Tensors")
print("="*60)

Part 3: Creating Random Tensors


In [17]:
# TODO: Set random seed for reproducibility
torch.manual_seed(42)

In [18]:
# TODO: Create random tensor from uniform distribution [0, 1)
rand_uniform = torch.rand(3, 4)
print(f"Random uniform (3x4):\n{rand_uniform}")

Random uniform (3x4):
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [19]:
# TODO: Create random tensor from normal distribution
rand_normal = torch.randn(2, 3)
print(f"Random normal (2x3):\n{rand_normal}")

Random normal (2x3):
tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])


In [20]:
# TODO: Create random integers
rand_int = torch.randint(low=0, high=10, size=(3, 5))
print(f"Random integers (3x5):\n{rand_int}")

Random integers (3x5):
tensor([[9, 3, 1, 9, 7],
        [9, 2, 0, 5, 9],
        [3, 4, 9, 6, 2]])


In [21]:
print("=" * 60)
print("Part 4: Working with NumPy")
print("=" * 60)

Part 4: Working with NumPy


In [22]:
# TODO: Create a NumPy array
np_array = np.array([[1, 2, 3], [5, 3, 2]])
print(f"NumPy array:\n{np_array}")

NumPy array:
[[1 2 3]
 [5 3 2]]


In [ ]:
# TODO: Convert NumPy array to PyTorch tensor
# numpy < 2.x
tensor_from_np = torch.from_numpy(np_array)
print(f"\nTensor from NumPy:\n{tensor_from_np}")




Tensor from NumPy:
tensor([[1, 2, 3],
        [5, 3, 2]])


In [25]:
# TODO: Convert PyTorch tensor to NumPy array
np_from_tensor = tensor_from_np.numpy()
print(f"\nNumPy from tensor:\n{np_from_tensor}")


NumPy from tensor:
[[1 2 3]
 [5 3 2]]


In [26]:
print("\n" + "=" * 60)
print("Part 5: Tensor Attributes")
print("=" * 60)


Part 5: Tensor Attributes


In [27]:
tensor = torch.rand(2, 3, 4)

In [29]:
print(tensor)

tensor([[[0.3423, 0.6343, 0.3644, 0.7104],
         [0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050]],

        [[0.3068, 0.1165, 0.9103, 0.6440],
         [0.7071, 0.6581, 0.4913, 0.8913],
         [0.1447, 0.5315, 0.1587, 0.6542]]])


In [28]:
# TODO: Print tensor shape
print(f"Shape: {tensor.shape}")

# TODO: Print tensor data type
print(f"Dtype: {tensor.dtype}")

# TODO: Print tensor device
print(f"Device: {tensor.device}")

# TODO: Print number of dimensions
print(f"Number of dimensions: {tensor.ndim}")

# TODO: Print total number of elements
print(f"Total elements: {tensor.numel()}")

Shape: torch.Size([2, 3, 4])
Dtype: torch.float32
Device: cpu
Number of dimensions: 3
Total elements: 24


In [31]:
print("\n" + "=" * 60)
print("Exercises")
print("=" * 60)


Exercises


In [32]:
# Exercise 1: Create a 4x4 tensor filled with the value 3.14
print("Exercise 1: Create a 4x4 tensor filled with 3.14")
ex1 = torch.full((4, 4), 3.14)
print(ex1)

Exercise 1: Create a 4x4 tensor filled with 3.14
tensor([[3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400]])


In [34]:
# Exercise 2: Create a random tensor of shape (5, 5) with values between 0 and 1
print("Exercise 2: Create random 5x5 tensor [0, 1)")
ex2 = torch.rand(5, 5)
print(ex2)

Exercise 2: Create random 5x5 tensor [0, 1)
tensor([[0.2477, 0.6524, 0.6057, 0.3725, 0.7980],
        [0.8399, 0.1374, 0.2331, 0.9578, 0.3313],
        [0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247],
        [0.0624, 0.1816, 0.9998, 0.5944, 0.6541]])


In [38]:
# Exercise 3: Create a tensor with values from 10 to 50 (exclusive) with step 5
print("Exercise 3: Range from 10 to 50 with step 5")
ex3 = torch.linspace(10, 50, steps=5)
print(ex3)

Exercise 3: Range from 10 to 50 with step 5
tensor([10., 20., 30., 40., 50.])


In [ ]:
# Exercise 4: Create a 3D tensor of shape (2, 3, 4) filled with ones
print("Exercise 4: Create 3D tensor (2, 3, 4) of ones")
ex4 = torch.ones(2, 3, 4)
print(ex4)


Exercise 4: Create 3D tensor (2, 3, 4) of ones
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [46]:
# Exercise 5: Check if a GPU is available and create a tensor on it if possible
print("Exercise 5: Create tensor on GPU if available")
if torch.cuda.is_available():
    torch.set_default_device('cuda')

    x_auto = torch.rand(2, 3)
    print(f"\nAuto-created on device: {x_auto.device}")

    y_auto = torch.rand(2, 3)
    print(f"\nReset to CPU device: {y_auto.device}")
else:
    print("GPU is unavailable")

Exercise 5: Create tensor on GPU if available
GPU is unavailable


In [47]:
print("\n" + "=" * 60)
print("Exercise 1 Complete!")
print("=" * 60)


Exercise 1 Complete!
