In [3]:
import torch

# Set random seed for reproducibility
torch.manual_seed(42)

In [4]:
print("=" * 60)
print("Part 1: Basic Arithmetic Operations")
print("=" * 60)

Part 1: Basic Arithmetic Operations


In [5]:
# Create test tensors
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([5, 3, 3, 2], dtype=torch.float32)

print(f"x: {x}")
print(f"y: {y}")

x: tensor([1., 2., 3., 4.])
y: tensor([5., 3., 3., 2.])


In [6]:
# TODO: Addition
add_result = x + y
print(f"Addition (x + y): {add_result}")

Addition (x + y): tensor([6., 5., 6., 6.])


In [7]:
# TODO: Subtraction
sub_result = x - y
print(f"Subtraction (x - y): {sub_result}")

Subtraction (x - y): tensor([-4., -1.,  0.,  2.])


In [8]:
# TODO: Element-wise multiplication
mul_result = x * y
print(f"Multiplication (x * y): {mul_result}")

Multiplication (x * y): tensor([5., 6., 9., 8.])


In [9]:
# TODO: Element-wise division
div_result = x / y
print(f"Division (x / y): {div_result}")

Division (x / y): tensor([0.2000, 0.6667, 1.0000, 2.0000])


In [10]:
# TODO: Power
pow_result = x**2
print(f"Power (x^2): {pow_result}")

Power (x^2): tensor([ 1.,  4.,  9., 16.])


In [11]:
print("\n" + "=" * 60)
print("Part 2: Matrix Operations")
print("=" * 60)


Part 2: Matrix Operations


In [12]:
A = torch.randn(3, 4)
B = torch.randn(4, 5)
print(f"Matrix A shape: \n{A.shape}\n{A}")
print(f"Matrix B shape: \n{B.shape}\n{B}")

Matrix A shape: 
torch.Size([3, 4])
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
Matrix B shape: 
torch.Size([4, 5])
tensor([[ 0.3559, -0.6866, -0.4934,  0.2415,  1.3123],
        [ 0.6872, -1.0892, -0.3553, -0.9138, -0.6581],
        [ 0.0780,  0.5258,  1.1790, -0.4345, -1.3864],
        [-1.2862, -1.4032,  0.0360, -0.0635,  0.6756]])


In [13]:
# TODO: Matrix multiplication
matmul_result = A @ B
print(f"\nMatrix multiplication A @ B shape: {matmul_result.shape}")


Matrix multiplication A @ B shape: torch.Size([3, 5])


In [14]:
# TODO: Transpose
A_T = A.T
print(f"Transpose of A shape: {A_T.shape}")
print(f"A: \n{A}")
print(f"A.T: \n{A_T}")


Transpose of A shape: torch.Size([4, 3])
A: 
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
A.T: 
tensor([[ 0.3367, -1.1229,  0.4617],
        [ 0.1288, -0.1863,  0.2674],
        [ 0.2345,  2.2082,  0.5349],
        [ 0.2303, -0.6380,  0.8094]])


In [15]:
# TODO: Element-wise min/max
min_val = torch.min(A)
max_val = torch.max(A)
print(f"\nMin value in A: {min_val:.4f}")
print(f"Max value in A: {max_val:.4f}")


Min value in A: -1.1229
Max value in A: 2.2082


In [16]:
print("\n" + "=" * 60)
print("Part 3: Reduction Operations")
print("=" * 60)


Part 3: Reduction Operations


In [17]:
# Create a 2D tensor
tensor = torch.randn(3, 4)
print(f"Tensor:\n{tensor}")

Tensor:
tensor([[-0.0085,  0.7291,  0.1331,  0.8640],
        [-1.0157, -0.8887,  0.1498, -0.2089],
        [-0.3870,  0.9912,  0.4679, -0.2049]])


In [18]:
# TODO: Sum all elements
sum_all = torch.sum(tensor)
print(f"Sum of all elements: {sum_all:.4f}")

Sum of all elements: 0.6213


In [19]:
# TODO: Sum along rows (dim=0)
sum_rows = torch.sum(tensor, dim=0)
print(f"Sum along rows: {sum_rows}")

Sum along rows: tensor([-1.4112,  0.8315,  0.7508,  0.4502])


In [20]:
# TODO: Sum along rows (dim=1)
sum_cols = torch.sum(tensor, dim=1)
print(f"Sum along columns: {sum_cols}")

Sum along columns: tensor([ 1.7177, -1.9635,  0.8672])


In [21]:
# TODO: Mean
mean_all = torch.mean(tensor)
print(f"Mean of all elements: {mean_all:.4f}")


Mean of all elements: 0.0518


In [23]:
# TODO: Standard deviation
std_all = torch.std(tensor)
print(f"Standard deviation: {std_all:.4f}")

Standard deviation: 0.6428


In [24]:
print("\n" + "=" * 60)
print("Part 4: Comparison Operations")
print("=" * 60)


Part 4: Comparison Operations


In [25]:
x = torch.tensor([1, 2, 3, 4, 5])
y = torch.tensor([2, 2, 4, 4, 6])

print(f"x: {x}")
print(f"y: {y}")

x: tensor([1, 2, 3, 4, 5])
y: tensor([2, 2, 4, 4, 6])


In [30]:
# TODO: Element-wise comparison
eq_result = x == y
print(f"\nEqual (x == y): {eq_result}")

gt_result = x >= y
print(f"Greater than (x > y): {gt_result}")

lt_result = x < y
print(f"Less than (x < y): {lt_result}")


Equal (x == y): tensor([False,  True, False,  True, False])
Greater than (x > y): tensor([False,  True, False,  True, False])
Less than (x < y): tensor([ True, False,  True, False,  True])


In [37]:
# TODO: Clamp values
clamped = torch.clamp(x, min=2, max=4)
print(f"\nClamp x to [2, 4]: {clamped}")


Clamp x to [2, 4]: tensor([2, 2, 3, 4, 4])


In [38]:
print("\n" + "=" * 60)
print("Part 5: Broadcasting")
print("=" * 60)


Part 5: Broadcasting


In [41]:
# Create tensors with different shapes
x = torch.randn(3, 1)
y = torch.randn(1, 4)

print(f"x shape: {x.shape}\n{x}")
print(f"y shape: {y.shape}\n{y}")

x shape: torch.Size([3, 1])
tensor([[-1.1267],
        [-0.2858],
        [-1.0935]])
y shape: torch.Size([1, 4])
tensor([[ 1.1351,  0.7592, -3.5945,  0.0192]])


In [42]:
# TODO: Broadcast addition
result = x + y
print(f"\nBroadcast result shape: {result.shape}")
print(f"Result:\n{result}")


Broadcast result shape: torch.Size([3, 4])
Result:
tensor([[ 0.0084, -0.3675, -4.7212, -1.1076],
        [ 0.8493,  0.4735, -3.8802, -0.2666],
        [ 0.0416, -0.3343, -4.6880, -1.0744]])


In [44]:
print("\n" + "=" * 60)
print("Exercises")
print("=" * 60)


Exercises


In [48]:
# Exercise 1: Given two matrices A (4x3) and B (3x5), compute C = A @ B
print("\nExercise 1: Matrix multiplication")
A = torch.randn(4, 3)
B = torch.randn(3, 5)

C = A @ B
print(f"Shape: {C.shape}")


Exercise 1: Matrix multiplication
Shape: torch.Size([4, 5])


In [59]:
# Exercise 2: Normalize a tensor to have zero mean and unit variance
print("\nExercise 2: Normalize tensor")
tensor = torch.randn(100, 10)
mean = torch.mean(tensor)
std = torch.std(tensor)
print(f"Mean before normalize: {mean}")
print(f"Standard deviation before normalize: {std}")

normalized_result = (tensor - mean)/std
normalized_mean = torch.mean(normalized_result)
normalized_std = torch.std(normalized_result)
print(f"Mean after normalize: {normalized_mean}")
print(f"Standard deviation after normalize: {normalized_std}")


Exercise 2: Normalize tensor
Mean before normalize: 0.007346520200371742
Standard deviation before normalize: 1.014809250831604
Mean after normalize: 6.675720420901143e-09
Standard deviation after normalize: 1.0


In [64]:
# Exercise 3: Find the indices of the top 3 values in a tensor
print("\nExercise 3: Find top 3 indices")
tensor = torch.randn(10)
# Find indices of top 3 values
# using topk
top_values, top_indices = torch.topk(tensor, 3)
print(top_indices)

# using argsort
indices = torch.argsort(tensor, descending=True)[:3]
print("Indices (using argsort):", indices)


Exercise 3: Find top 3 indices
tensor([9, 0, 7])
Indices (using argsort): tensor([9, 0, 7])


In [78]:
# Exercise 4: Implement softmax function
print("\nExercise 4: Implement softmax")
logits = torch.randn(2, 5)  # Batch of 2, 5 classes
# Implement: softmax(x) = exp(x) / sum(exp(x))
exp = torch.exp(logits)
print(exp)
# dim=1: We sum across the columns (the classes).
# keepdim=True: Keeps the shape as (2, 1) instead of (2), allowing for broadcasting later.
sum_exp = torch.sum(exp, dim=1, keepdim=True)
print(sum_exp)
# PyTorch broadcasts (2, 5) / (2, 1) automatically
softmax = exp / sum_exp
print("\nImplement softmax\n", softmax)
# Built-in function to check
built_softmax = torch.softmax(logits, dim=1)
print("\nBuilt-in Softmax:\n", built_softmax)


Exercise 4: Implement softmax
tensor([[0.7509, 1.5690, 4.5636, 4.0303, 3.6650],
        [0.3704, 1.4292, 0.4766, 0.4282, 1.3567]])
tensor([[14.5788],
        [ 4.0611]])

Implement softmax
 tensor([[0.0515, 0.1076, 0.3130, 0.2764, 0.2514],
        [0.0912, 0.3519, 0.1174, 0.1054, 0.3341]])

Built-in Softmax:
 tensor([[0.0515, 0.1076, 0.3130, 0.2764, 0.2514],
        [0.0912, 0.3519, 0.1174, 0.1054, 0.3341]])


In [81]:
# Exercise 5: Compute cosine similarity between two vectors
print("\nExercise 5: Cosine similarity")
v1 = torch.randn(100)
v2 = torch.randn(100)
# Compute cosine similarity: (v1 . v2) / (||v1|| * ||v2||)

# dot product (v1 . v2)
dot_product = torch.dot(v1, v2)

# Magnitudes (||v1|| and ||v2||)
norm_v1 = torch.norm(v1)
norm_v2 = torch.norm(v2)

# Compute Cosine Similarity
cosine_sim = dot_product / (norm_v1 * norm_v2)

print("Cosine similarity: ", cosine_sim)

# Built-in function
import torch.nn.functional as F
# dim=0 means we compute similarity along the vector dimension.
cosine_sim_builtin = F.cosine_similarity(v1, v2, dim=0)

print(f"Built-in Cosine Similarity: {cosine_sim_builtin.item():.4f}")



Exercise 5: Cosine similarity
Cosine similarity:  tensor(0.0503)
Built-in Cosine Similarity: 0.0503


In [55]:
print("\n" + "=" * 60)
print("Exercise 2 Complete!")
print("=" * 60)


Exercise 2 Complete!
