In [1]:
"""
Exercise 3: Tensor Manipulation
PyTorch Fundamentals - Module 1

This exercise covers:
- Reshaping tensors
- Indexing and slicing
- Transposing and permuting
- Squeezing and unsqueezing
- Concatenating and splitting tensors

PyTorch 2.0 Note: All manipulation operations are compatible with PyTorch 2.0.
See the device management section for torch.set_default_device() (PyTorch 2.0+ feature).
"""

'\nExercise 3: Tensor Manipulation\nPyTorch Fundamentals - Module 1\n\nThis exercise covers:\n- Reshaping tensors\n- Indexing and slicing\n- Transposing and permuting\n- Squeezing and unsqueezing\n- Concatenating and splitting tensors\n\nPyTorch 2.0 Note: All manipulation operations are compatible with PyTorch 2.0.\nSee the device management section for torch.set_default_device() (PyTorch 2.0+ feature).\n'

In [2]:
import torch

# Set random seed for reproducibility
torch.manual_seed(42)

In [3]:
print("=" * 60)
print("Part 1: Reshaping Tensors")
print("=" * 60)

Part 1: Reshaping Tensors


In [4]:
# Create a 1D tensor
x = torch.arange(12)
print(f"Original tensor: {x}")
print(f"Original shape: {x.shape}")

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])


In [7]:
# TODO: Reshape to 3x4
reshaped = x.reshape(3, 4)
print(f"\nReshaped to (3, 4):\n{reshaped}")


Reshaped to (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
# TODO: Reshape to 2x6
reshaped_2x6 = x.reshape(2, 6)
print(f"\nReshaped to (2, 6):\n{reshaped_2x6}")


Reshaped to (2, 6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [11]:
# TODO: Flatten to 2D tensor
flat = reshaped.flatten()
print(f"\nFlattened: {flat}")



Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [17]:
# TODO: Reshape with view (only works on contiguous tensors)
viewed = reshaped_2x6.view(-1)  # -1 means infer dimension
print(f"\nViewed as 1D: {viewed}")


Viewed as 1D: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [18]:
print("\n" + "=" * 60)
print("Part 2: Squeeze and Unsqueeze")
print("=" * 60)


Part 2: Squeeze and Unsqueeze


In [21]:
# Create tensor with singleton dimensions
x = torch.randn(2, 1, 4, 1)
print(f"Original shape: {x.shape}\n{x}")

Original shape: torch.Size([2, 1, 4, 1])
tensor([[[[ 1.3221],
          [ 0.8172],
          [-0.7658],
          [-0.7506]]],


        [[[ 1.3525],
          [ 0.6863],
          [-0.3278],
          [ 0.7950]]]])


In [24]:
# TODO: Remove all singleton dimensions
squeezed = x.squeeze()
print(f"After squeeze: {squeezed.shape}\n{squeezed}")

After squeeze: torch.Size([2, 4])
tensor([[ 1.3221,  0.8172, -0.7658, -0.7506],
        [ 1.3525,  0.6863, -0.3278,  0.7950]])


In [27]:
# TODO: Remove specific singleton dimension
squeezed_dim = x.squeeze(dim=1)
print(f"After squeeze(dim=1): {squeezed_dim.shape}\n{squeezed_dim}")

After squeeze(dim=1): torch.Size([2, 4, 1])
tensor([[[ 1.3221],
         [ 0.8172],
         [-0.7658],
         [-0.7506]],

        [[ 1.3525],
         [ 0.6863],
         [-0.3278],
         [ 0.7950]]])


In [31]:
# TODO: Add dimension at position 0
unsqueezed_0 = squeezed.unsqueeze(dim=0)
print(f"\nAfter unsqueeze(dim=0): {unsqueezed_0.shape}")


After unsqueeze(dim=0): torch.Size([1, 2, 4])


In [33]:
# TODO: Add dimension at last position
unsqueezed_last = squeezed.unsqueeze(dim=-1)
print(f"\nAfter unsqueeze(dim=-1): {unsqueezed_last.shape}")


After unsqueeze(dim=-1): torch.Size([2, 4, 1])


In [34]:
print("\n" + "=" * 60)
print("Part 3: Transpose and Permute")
print("=" * 60)


Part 3: Transpose and Permute


In [37]:
# Create a 3D tensor
x = torch.rand(2, 3, 4)
print("Original 3D tensor: ", x.shape)

Original 3D tensor:  torch.Size([2, 3, 4])


In [38]:
# TODO: Transpose dimensions 0 and 1
transposed = torch.transpose(x, 0, 1)
print(f"After transpose(0, 1): {transposed.shape}")

After transpose(0, 1): torch.Size([3, 2, 4])


In [41]:
# TODO: Permute all dimensions
permuted = x.permute(2, 0, 1)
print(f"After permute(2, 0, 1): {permuted.shape}")

After permute(2, 0, 1): torch.Size([4, 2, 3])


In [42]:
# TODO: Matrix transpose for 2D tensor
matrix = torch.randn(3, 4)
print(f"\nMatrix shape: {matrix.shape}")
print(f"Matrix.T shape: {matrix.T.shape}")


Matrix shape: torch.Size([3, 4])
Matrix.T shape: torch.Size([4, 3])


In [43]:
print("\n" + "=" * 60)
print("Part 4: Indexing and Slicing")
print("=" * 60)


Part 4: Indexing and Slicing


In [ ]:
# Create a 2D tensor
x = torch.arange(20).reshape(4, 5)
print(f"Tensor:\n{x}")

Tensor:
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


In [45]:
# TODO: Get element at position (1, 2)
element = x[1, 2]
print(f"\nElement at [1, 2]: {element}")


Element at [1, 2]: 7


In [46]:
# TODO: Get first row
first_row = x[0, :]
print(f"\nFirst row: {first_row}")


First row: tensor([0, 1, 2, 3, 4])


In [47]:

# TODO: Get last column
last_col = x[:, -1]
print(f"Last column: {last_col}")

Last column: tensor([ 4,  9, 14, 19])


In [48]:

# TODO: Get submatrix (rows 1-2, cols 2-4)
submatrix = x[1:3, 2:5]
print(f"\nSubmatrix [1:3, 2:5]:\n{submatrix}")


Submatrix [1:3, 2:5]:
tensor([[ 7,  8,  9],
        [12, 13, 14]])


In [50]:

# TODO: Boolean indexing
mask = x > 10
print(mask)
values = x[mask]
print(f"\nValues > 10: {values}")

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])

Values > 10: tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])


In [51]:

print("\n" + "=" * 60)
print("Part 5: Concatenating and Splitting")
print("=" * 60)


Part 5: Concatenating and Splitting


In [52]:

# Create tensors to concatenate
x1 = torch.randn(2, 3)
x2 = torch.randn(2, 3)
x3 = torch.randn(2, 3)

print(f"x1 shape: {x1.shape}")
print(f"x2 shape: {x2.shape}")

x1 shape: torch.Size([2, 3])
x2 shape: torch.Size([2, 3])


In [53]:

# TODO: Stack along new dimension (dim=0)
stacked = torch.stack([x1, x2, x3], dim=0)
print(f"\nStacked along dim=0: {stacked.shape}")


Stacked along dim=0: torch.Size([3, 2, 3])


In [59]:

# TODO: Concatenate along existing dimension (dim=0)
concat_dim0 = torch.cat([x1, x2, x3], dim=0)
print(f"Concatenated along dim=0: {concat_dim0.shape}")
# dim=-1 -> torch.Size([2, 9])

Concatenated along dim=0: torch.Size([6, 3])


In [62]:

# TODO: Split tensor into chunks
x = torch.randn(6, 4)
chunks = torch.chunk(x, chunks=3, dim=0)
print(f"\nSplit into 3 chunks along dim=0:")
for i, chunk in enumerate(chunks):
    print(f"  Chunk {i} shape: {chunk.shape}")


Split into 3 chunks along dim=0:
  Chunk 0 shape: torch.Size([2, 4])
  Chunk 1 shape: torch.Size([2, 4])
  Chunk 2 shape: torch.Size([2, 4])


In [64]:

# TODO: Split at specific indices
split_sections = torch.split(x, [2, 4], dim=0)
print(f"\nSplit into sections of size [2, 4]:")
for i, section in enumerate(split_sections):
    print(f"  Section {i} shape: {section.shape}")


Split into sections of size [2, 4]:
  Section 0 shape: torch.Size([2, 4])
  Section 1 shape: torch.Size([4, 4])


In [65]:
print("\n" + "=" * 60)
print("Exercises")
print("=" * 60)


Exercises


In [70]:

# Exercise 1: Given a tensor of shape (64, 1, 28, 28), remove the singleton dimension
print("\nExercise 1: Remove singleton dimension")
x = torch.randn(64, 1, 28, 28)
ex1 = x.squeeze()
print(ex1.shape)


Exercise 1: Remove singleton dimension
torch.Size([64, 28, 28])


In [73]:

# Exercise 2: Add a batch dimension to a single image tensor of shape (3, 224, 224)
print("\nExercise 2: Add batch dimension")
image = torch.randn(3, 224, 224)
ex2 = image.unsqueeze(dim=0)
print(ex2.shape)



Exercise 2: Add batch dimension
torch.Size([1, 3, 224, 224])


In [75]:
# Exercise 3: Convert HWC format to CHW format
print("\nExercise 3: HWC to CHW conversion")
hwc_image = torch.randn(224, 224, 3)
# should result in (3, 224, 224)
ex3 = torch.transpose(hwc_image, 0, 2)
print(ex3.shape)



Exercise 3: HWC to CHW conversion
torch.Size([3, 224, 224])


In [84]:

# Exercise 4: Extract the diagonal elements from a square matrix
print("\nExercise 4: Extract diagonal")
matrix = torch.randn(5, 5)
values = []
print(matrix)
for i in range(5):
    values.append(matrix[i][i])
print(f"\nThe diagonal elements: {values}")



Exercise 4: Extract diagonal
tensor([[-1.3770, -0.9745,  0.2242, -0.6501,  1.4129],
        [-1.7925, -1.0728,  0.5048,  0.2844,  0.8771],
        [ 0.6538, -0.1577, -0.3949, -0.5205, -2.1618],
        [-0.0258,  0.0577, -0.2007, -0.6989, -0.7955],
        [ 0.2813,  0.3652, -0.2463, -0.9683,  0.5031]])

The diagonal elements: [tensor(-1.3770), tensor(-1.0728), tensor(-0.3949), tensor(-0.6989), tensor(0.5031)]


In [90]:
# Exercise 5: Create a batch of 10 random images and stack them
print("\nExercise 5: Stack images into batch")
images = [torch.randn(3, 224, 224) for _ in range(10)]
# Should result in (10, 3, 224, 224)
ex5 = torch.stack(images, dim=0)
print(ex5.shape)


Exercise 5: Stack images into batch
torch.Size([10, 3, 224, 224])


In [76]:
print("\n" + "=" * 60)
print("Exercise 3 Complete!")
print("=" * 60)


Exercise 3 Complete!
